version: "3.8"
services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../:/workspaces:cached  
    network_mode: service:postgres
    command: sleep infinity

  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/data/auth-db
    environment:
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres-data: